'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace CustomHeaderButtonsExample.Properties

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(CustomHeaderButtonsExample.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(CustomHeaderButtonsExample.Properties.Resources).Assembly)
                    CustomHeaderButtonsExample.Properties.Resources.resourceMan = temp
                End If

                Return CustomHeaderButtonsExample.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return CustomHeaderButtonsExample.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                CustomHeaderButtonsExample.Properties.Resources.resourceCulture = value
            End Set
        End Property

        Friend Shared ReadOnly Property center_align_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("center-align-16x16", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property delete_pressed As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("delete-pressed", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Float As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("Float", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property item As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("item", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property left_align_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("left-align-16x16", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Pinned As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("Pinned", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property right_align_16x16 As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("right-align-16x16", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property Selected As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("Selected", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        Friend Shared ReadOnly Property unselected As System.Drawing.Bitmap
            Get
                Dim obj As Object = CustomHeaderButtonsExample.Properties.Resources.ResourceManager.GetObject("unselected", CustomHeaderButtonsExample.Properties.Resources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
